{{- $target_env := .Values.env.staging -}}
{{- if .Values.prod }}
  {{- $target_env = .Values.env.prod }}
{{- end -}}

apiVersion: v1
kind: Service
metadata:
  name: doc
spec:
  selector:
    app: doc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: doc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doc
  template:
    metadata:
      labels:
        app: doc
    spec:
      serviceAccountName: {{ $target_env.k8s_sa }}
      containers:
        - name: doc
          image: {{ .Values.image }}
          ports:
            - containerPort: 8080
