name: Generate Reliably CLI Documentation

on:
  workflow_dispatch
  repository_dispatch:
    types: [gen-cli-doc]

jobs:
  gen-cli-doc:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout source code'
      uses: actions/checkout@v2
    - name: Setup Reliably CLI latest version
      id: reliably
      uses: reliablyhq/gh-action/setup@v1
    - name: Generate CLI doc
      run: reliably doc markdown --output-dir cobra-md
    - name: Commit Documentation
      run: |
        git config user.email "74009226+reliably-ci@users.noreply.github.com"
        git config user.name "CI at Reliably"

        git add cobra-md/*; RC=$? && \
        git commit -s -m "Generate documentation for ${{ steps.reliably.outputs.version }}" && \
        git push && \
        [ $RC -eq 0 ] && echo "doc changes were pushed" || echo "no changes"

