name: Generate Reliably CLI Documentation

on:
  workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout source code'
      uses: actions/checkout@v2
    - name: Setup Reliably CLI latest version
      id: reliably
      uses: reliablyhq/gh-action/setup@v1
    - name: Generate CLI doc
      run: reliably doc markdown --output-dir cobra-md
    - name: Commit Documentation
      run: |
        git add -u
        git commit -s -m "Generate documentation for Reliably CLI version ${{ steps.reliably.outputs.version }}"

