name: Trigger Prod Workflow via Main Tag 
on:
  workflow_dispatch:

jobs:
  tag-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: 'main'
          token: ${{ secrets.GH_PAT }}
      - name: Tag and push
        if: ${{ !env.ACT }}
        run: |
          git tag $(date +%Y%m%dT%H%M%S)
          git push --tags