name: Release Docs
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'cobra-md/**.md'

jobs:
  tag-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: 'main'
          token: ${{ secrets.GH_PAT }}
          repository: 'reliablyhq/documentation'
      - name: Tag and push
        if: ${{ !env.ACT }}
        run: |
          git config user.email "74009226+reliably-ci@users.noreply.github.com"
          git config user.name "CI at Reliably"
          git tag $(date +%Y%m%dT%H%M%S)
          git push --tags